services:
  mc_1_21_5:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: latest
      TYPE: NEOFORGE
      NEOFORGE_VERSION: beta
#      MODPACK_PLATFORM: MODRINTH
#      MODRINTH_MODPACK: https://modrinth.com/modpack/plus200-modpack/version/1.0.0
      MODS_FILE: /extras/mods.txt
#      MODS: |
#        /mc-mods/multiworld/output/Multiworld-NeoForged-1.21.2.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
      - ./mods_1_21_5.txt:/extras/mods.txt:ro
      - ../:/mc-mods
    stdin_open: true
    tty: true
    restart: unless-stopped

  mc_1_21_1:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.21.1"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: latest
      MODS_FILE: /extras/mods.txt
#      FORGE_FORCE_REINSTALL: true
#      MODS: |
#        /mc-mods/multiworld/output/Multiworld-NeoForged-1.21.1.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data_1_21_1:/data
      - ./mods_1_21_1.txt:/extras/mods.txt:ro
      - ../:/mc-mods
    stdin_open: true
    tty: true
    restart: unless-stopped

  mc_1_21_2:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.21.2"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: beta
      MODS_FILE: /extras/mods.txt
#      FORGE_FORCE_REINSTALL: true
#      MODS: |
#        /mc-mods/multiworld/output/Multiworld-NeoForged-1.21.2.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data_1_21_2:/data
      - ./mods_1_21_2.txt:/extras/mods.txt:ro
      - ../:/mc-mods
    stdin_open: true
    tty: true
    restart: unless-stopped

  mc_1_21_3:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.21.3"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: latest
      MODS_FILE: /extras/mods.txt
#      FORGE_FORCE_REINSTALL: true
#      MODS: |
#        /mc-mods/multiworld/output/Multiworld-NeoForged-1.21.2.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data_1_21_3:/data
      - ./mods_1_21_3.txt:/extras/mods.txt:ro
      - ../:/mc-mods
    stdin_open: true
    tty: true
    restart: unless-stopped

  mc_1_21_4:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.21.4"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: latest
      MODS_FILE: /extras/mods.txt
#      FORGE_FORCE_REINSTALL: true
#      MODS: |
#        /mc-mods/multiworld/output/Multiworld-NeoForged-1.21.2.jar
    ports:
      - "25565:25565"
    volumes:
      - ./data_1_21_4:/data
      - ../:/mc-mods
      - ./mods_1_21_4.txt:/extras/mods.txt:ro
    stdin_open: true
    tty: true
    restart: unless-stopped

  civilization:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      VERSION: "1.21.4"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: latest
      FORGE_FORCE_REINSTALL: true
      MODS_FILE: /extras/mods.txt
      SEED: "-1515581825"
      ICON: https://raw.githubusercontent.com/jblemee/PermaDeath/refs/heads/main/src/main/resources/permadeath.png
      MAX_PLAYERS: 1000
      MAX_WORLD_SIZE: 40000
      BUG_REPORT_LINK: https://github.com/jblemee/Civilization/issues/new
      DIFFICULTY: normal
      REQUIRE_RESOURCE_PACK: false
      RESOURCE_PACK_ID: "a1259812-d2c2-310d-9a7d-2590d9ad6a32"
      RESOURCE_PACK: https://github.com/jblemee/DiceMC-Money-Mod/releases/download/1.21.3/client-resource-pack.zip
      MOTD: |
        §l§cCivilization§r Server
        The §l§4permanent death§r experiment
      MEMORY: ""
      OPS: |
        Plus200
      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - "25565:25565"
    volumes:
      - ./data_civ:/data
      - ../:/mc-mods
      - ./civilization.txt:/extras/mods.txt:ro
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  data: {}
  data_1_21_1: {}
  data_1_21_2: {}
  data_1_21_3: {}
  data_1_21_4: {}
  data_civ: {}